version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4

    links:
      - postgres:postgres

    ports:
      - "9001:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: rick@devhausleipzig.de
      PGADMIN_DEFAULT_PASSWORD: schwifty

  adminer:
    image: adminer:4.7.7-standalone

    links:
      - postgres:postgres

    ports:
      - "9000:8080"

  postgres:
    image: postgres:13.0

    environment:
      POSTGRES_DB: spark
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark

    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw

    ports:
      - "5432:5432/tcp"
